### ISSUE TITLE
Integrate webpack

### ISSUE THREAD

**Issue by OmTheTurtle** [kir-dev/tanulo-next#107]
Use webpack for asset compilation and bundling. With this we can also use yarn for front-end dependencies (instead of CDN).

**Comment by triszt4n** [comment]
> Other thing that makes me wondering, there are many packages imported from cdn, which is good, but without any specified version. I'm not sure how often there are breaking changes and failing versions, neither if there is any option to specify a version here, just wanted to mention it, maybe it is worth a new issue. (#250)

**Comment by triszt4n** [comment]
I'm thinking about, that maybe we don't need webpack after all, tailwind says, css compilation could be a little bit longer.

**Comment by OmTheTurtle** [comment]
The main advantage of a bundler (we can use vite / snowpack / rollup / etc) is the JS compilation step for the frontend scripts (we can still use postcss-cli for tailwind). With that we can eliminate the use of CDNs and use modern features like bundling / transpiling for FE code, of course for now it's just a nice-to-have feature.
