### ISSUE TITLE
Fix little bugs

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/tanulo-next#219]
#### Typo:
migrations/20200408124626_add_non_nullable.ts line 25: `'tikcets'` should be `'tickets'`

#### Semantic error:
components/groups/group.middlewares.ts line 23: `.where('id', (req.user as User).id)` should be `.where('user_id', (req.user as User).id)`

**Comment by OmTheTurtle** [comment]
For the second one: I think it's not a bug, the `id` references the `user.id` in the `users` table (see [here](https://vincit.github.io/objection.js/guide/query-examples.html#relation-unrelate-queries).

**Comment by triszt4n** [comment]
Gonna look into it once again, but I tried leaving with the original code, wrote a catch block, and after rewriting to `user_id`, it worked flawlessly.

**Comment by triszt4n** [comment]
So, I looked into it, we get this error with the original code:
`DBError: delete from "users_groups" where "users_groups"."user_id" in (select "users"."id" from "users" inner join "users_groups" on "users"."id" = "users_groups"."user_id" where "users_groups"."group_id" in ($1) and "id" = $2) and "users_groups"."group_id" in ($3) - column reference "id" is ambiguous`
So I suggest we change the line in question to this:
`.where('users.id', (req.user as User).id)`
So that it should be clear, which id to use.

**Comment by OmTheTurtle** [comment]
Thanks for clarification, will fix right away.
