### ISSUE TITLE
Download group event as ics on group show

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/tanulo-next#220]
Make a button, that exports an .ics file, that can be imported into a calendar app. Packages like ics, file-saver and blob might be useful, but strive for light-weight implementation.

**Comment by OmTheTurtle** [comment]
I started implementing this and have great progress, importing in Google Calendar event the description formatting is getting displayed correctly :tada: 

I was thinking about that maybe whole floors could be generated and imported for a user.
The best thing for this would be to create a calendar that could be updated every time a new event created at the floor. But this is for later and for a separate issue, just mentioning.
