### ISSUE TITLE
Implement email notification system

### ISSUE THREAD

**Issue by OmTheTurtle** [kir-dev/tanulo-next#253]
The app could send an email to KBPR whenever a new Ticket is created.

**Comment by nmate980829** [comment]
I tried to use the [nodemailer](https://www.npmjs.com/package/nodemailer) package with [direct transport](https://www.npmjs.com/package/nodemailer-direct-transport). I tried it on aws with an SPF record, but I couldn't get it to work. I think we should create an e-mail address for the app and just simply use the standard SMTP transport.
