### ISSUE TITLE
Make the dates on groups' page more verbose

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/tanulo-next#255]
#### Problem:
People have a hard time remembering even today's date. Now the footer shows a full date-time of the start and end of event.
#### Solution:
We need something like "starting: in 5 minutes" and "duration: 45 minutes" in the footer. The group show page can stay as it is. Try implementing some functions. (A package would be too much(?))

**Comment by OmTheTurtle** [comment]
We have the [date-fns](https://date-fns.org/v2.13.0/docs/formatDistance) library in the project which I think can be used to achieve this.
