### ISSUE TITLE
Calendar shows events with wrong time

### ISSUE THREAD

**Issue by vankodg** [kir-dev/tanulo-next#256]
I suppose the calendar shows the events in wrong time zone. E.g. an event from 18:30 to 20:00, in the calendar it looks like it is from 20:30 to 22:00

**Comment by OmTheTurtle** [comment]
It looks like the docker container's timezone in prod is out of sync with the host machine.

**Comment by OmTheTurtle** [comment]
> It looks like the docker container's timezone in prod is out of sync with the host machine.

This might not be the root cause, but there's something with docker and the calendar plugin, because on a non-docker env everything works fine. :thinking:
