### ISSUE TITLE
Make session last for a week

### ISSUE THREAD

**Issue by OmTheTurtle** [kir-dev/tanulo-next#435]

**Comment by vercibar** [comment]
What does session refer to exactly in this context? I originally interpreted it as the default length of a group session, however it has come to my attention that the purpose of this issue may be different. Some unnamed individual has brought it to my attention that this issue in fact, may refer to the time it takes for the session cookies to become obsolete. Please confirm the purpose of this very matter.
Sincerely, Master Kovács

**Comment by OmTheTurtle** [comment]
The intention was to make the user login last longer, so the don't have to login so often. Sorry for the ambiguity.
