### ISSUE TITLE
Change ticket visibility

### ISSUE THREAD

**Issue by OmTheTurtle** [kir-dev/tanulo-next#458]
By default, users should only see tickets they created themselves and admins should have full access. For this we need to add a new field (userId) to the ticket model to join the two tables.

**Comment by triszt4n** [comment]
Well, this deprives simple users from seeing, if there's a problem already in a study room. Or maybe worse: users might flood the the system with the same tickets, because they don't know if the ticket already exists.

**Comment by OmTheTurtle** [comment]
> Well, this deprives simple users from seeing, if there's a problem already in a study room. Or maybe worse: users might flood the the system with the same tickets, because they don't know if the ticket already exists.

You're right, I didn't think about these use cases. In this case a simple toggle to switch between "all" and "only my tickets" would be sufficient.

**Comment by triszt4n** [comment]
> In this case a simple toggle to switch between "all" and "only my tickets" would be sufficient.

I like this idea 💯
