### ISSUE TITLE
Give feedback on successful personal configurations saving

### ISSUE THREAD

**Issue by gmarci11** [kir-dev/tanulo-next#562]
![image](https://user-images.githubusercontent.com/42243742/111083139-3463f580-850c-11eb-9a8b-f17f658a99e8.png)

We should give some kind of feedback on successfully saved changins on 'personal configurations' page. The lack of it could be a bit disturbing for a moment if the changing actually has happened or not.

**Comment by nmate980829** [comment]
There is a favourite rooms function which will be merged once I updated the ui. That function makes this one obsolete, thus the PR removes it.
